const jwtSecret = 'BRahujBqkZDAHMtYKoPP';
const bugzillaToken = "1-G54RtNO8R8";
const bugzillaHost = "http://ec2-34-209-73-50.us-west-2.compute.amazonaws.com";
const bugzillaBaseURL = bugzillaHost + "/bugzilla/rest";
const bugzillaProductPrefix = "MobileTaas";
const S3_BUCKET = "cmpe-281-mobile-taas-resumes";
const AWS_ACCESS_KEY_ID = "AKIA42KYJYLTMWQNT6HF";
const AWS_SECRET_ACCESS_KEY = "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";
module.exports = {jwtSecret, bugzillaToken, bugzillaBaseURL, bugzillaProductPrefix, bugzillaHost,S3_BUCKET,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY};
